root: true

extends:
  - eslint:recommended

env:
  browser: true
  amd: true

globals:
  $: false
  escapeHTML: false
  OC: false
  OCA: false
  t: false
  Backbone: false
  _: false
  oc_current_user: false
  Clipboard: false
  oc_defaults: false

rules:
  curly: error
  eqeqeq: ["error", "smart"]
  guard-for-in: error
  no-console: off
  no-fallthrough: error
  no-mixed-spaces-and-tabs: error
  no-unused-vars: error
  no-use-before-define: error
  semi: ["error", "always"]
